on:
  push:
    branches:
    - build-android
  workflow_dispatch:

permissions:
  contents: read

name: Build Android Dependencies
jobs:

  build-android:
    name: android ${{matrix.architecture}} static
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        architecture: [ arm64, arm, x64, x86 ]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          persist-credentials: false

      - name: Install tools
        run: ./.github/build/android-${{matrix.architecture}}/install.sh

      - name: Clone dependencies
        run: ./clone-dependencies.sh android

      - name: Build
        run: ./.github/build/android-${{matrix.architecture}}/build.sh

      - name: Generate SBOM
        run: python3 .github/build/shared/generate-sbom.py Artifacts/sbom.json

      - name: Prepare artifacts
        run: |
          cp -r /tmp/dependencies/lib Artifacts
          cp -r /tmp/dependencies/include Artifacts
          cd Artifacts
          zip -r ../android-${{matrix.architecture}}-static.zip .

      - name: Upload artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f #v7.0.0
        with:
          name: android-${{matrix.architecture}}-static
          path: android-${{matrix.architecture}}-static.zip