on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/check-for-new-releases.yml
    - check-releases.sh

permissions:
  contents: read

name: Check for new releases of dependencies
jobs:
  dependency-releases:
    name: Check for new releases
    runs-on: windows-2025-vs2026

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          persist-credentials: false

      - name: Clone dependencies
        shell: cmd
        run: clone-dependencies.cmd

      - name: Check releases
        shell: cmd
        run: check-releases.cmd
